services:
  postgres:
    image: postgres:15.3
    container_name: grocery-store-backend-postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ADMSTA
    command: -p 5433
volumes:
  postgres-data:
