### executions
GET  http://localhost:8005/api/v1/executions?orderDirection=desc&pageIndex=0&pageSize=20
Content-Type: application/json
x-sta-tenant: stoneage
x-sta-userid: user@email.com


### executions/:executionId
GET  http://localhost:8005/api/v1/executions/09c66481-6bad-4c90-bdf7-52a37d8b3df2
Content-Type: application/json
x-sta-tenant: stoneage
x-sta-userid: user@email.com
