export const injection = {
  infra: {
    marketRepositories: 'market-repositories',
    userRepositories: 'user-repositories',
    familyRepositories: 'family-repositories',
    shoppingEventRepositories: 'shopping-event-repositories',
    productRepositories: 'product-repositories',
  },
  usecases: {
    newMarket: 'new-market-usecase',
    updateMarket: 'update-market-usecase',
    getMarketList: 'get-market-list-usecase',
    getMarketById: 'get-market-by-id-usecase',
    startShoppingEvent: 'start-shopping-event-usecase',
    endShoppingEvent: 'end-shopping-event-usecase',
    getShoppingEventList: 'get-shopping-event-list-usecase',
    getShoppingEventById: 'get-shopping-event-by-id-usecase',
    addProductToCart: 'add-product-to-cart-usecase',
    updateProductInCart: 'update-product-in-cart-usecase',
    removeProductFromCart: 'remove-product-from-cart-usecase',
    getUser: 'get-user-usecase',
    addFamily: 'add-family-usecase',
    joinFamily: 'join-family-usecase',
    leaveFamily: 'leave-family-usecase',
    getFamily: 'get-family-usecase',
  },
  controllers: {
    newMarket: 'new-market-controller',
    updateMarket: 'update-market-controller',
    getMarketList: 'get-market-list-controller',
    getMarketById: 'get-market-by-id-controller',
    startShoppingEvent: 'start-shopping-event-controller',
    endShoppingEvent: 'end-shopping-event-controller',
    getShoppingEventList: 'get-shopping-event-list-controller',
    getShoppingEventById: 'get-shopping-event-by-id-controller',
    addProductToCart: 'add-product-to-cart-controller',
    updateProductInCart: 'update-product-in-cart-controller',
    removeProductFromCart: 'remove-product-from-cart-controller',
    addFamily: 'add-family-controller',
    joinFamily: 'join-family-controller',
    leaveFamily: 'leave-family-controller',
    getFamily: 'get-family-controller',
  },
};
